### ISSUE TITLE
Symbol Lookup

### ISSUE THREAD

**Issue by shaps80** [stormwarning/vscode-jsont#1]
This is a great little extension and I'm using it every day. One thing that's a little frustrating though is that although I'm dealing essentially with HTML files I can't use the symbol lookup in VS Code to find classes, divs, etc...

I have to keep changing the Language Mode back and forth.

I looked over the files in this repo but I'm unclear as to how to add support for this, similar to how the Handlebars extensions do.

Any chance you could add this, or indicate where I should look to do this myself?

Appreciate any help/feedback.

**Comment by stormwarning** [comment]
Sure thing, I'll take a look at how the Handlebars extension is set up 👍

**Comment by shaps80** [comment]
Thanks for getting back to me quickly,

Great! Not to rush you, but would be nice to get to this ASAP, so if you're short on time, but could point me in the right direction – any help deeply appreciated :)

**Comment by stormwarning** [comment]
I thought it might have something to do with the `injections` key, but removing that didn't seem to enable the symbol lookup.

It looks like the Handlebars grammar includes `text.html.basic` but also has some HTML patterns of its own included here: 

https://github.com/Microsoft/vscode/blob/2ef1c7583ce4c566038ffc9a4a0e20efc3d128df/extensions/handlebars/syntaxes/Handlebars.tmLanguage.json#L46

Adding those in might work. Other than that, I'm not sure what else it could be, aside from some built-in language server magic on VS Code's end. Hope that helps — I appreciate you looking into it!

**Comment by shaps80** [comment]
Yeah I noticed that but wasn’t sure as I’m not familiar with these plugins. 

What’s the best way to test this? Where do these files get stored? So I can modify them and test. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stormwarning** [comment]
If you clone the repo and open it in VS Code, you hit <kbd>f5</kbd> — or go to Debug > Start Debugging — and it'll open a new editor window with the local extension loaded.

**Comment by shaps80** [comment]
Oh wow. Nice! I love this editor. Thanks for the hint!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
@stormwarning after some further research I think a Language Server is required for this features :(

https://code.visualstudio.com/docs/extensionAPI/language-support#_show-all-symbol-definitions-within-a-document

**Comment by stormwarning** [comment]
Shoot, I was afraid of that 😕 Still, I'll leave this open in case a solution can be found. Thanks for investigating!
